name: Compiler Optimization Benchmark

on:
  push:
    branches:
      - main

jobs:

  benchmark:

    runs-on: ubuntu-latest

    steps:

      # --------------------------------
      # CHECKOUT REPOSITORY
      # --------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --------------------------------
      # SETUP PYTHON
      # --------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      # --------------------------------
      # INSTALL LLVM 14 + GCC
      # --------------------------------
      - name: Install LLVM and GCC
        run: |
          sudo apt update

          sudo apt install -y \
            llvm-14 \
            clang-14 \
            libclang-14-dev \
            gcc \
            g++

      # --------------------------------
      # INSTALL PYTHON PACKAGES
      # --------------------------------
      - name: Install Python Packages
        run: |
          pip install flask
          pip install pandas
          pip install matplotlib
          pip install scikit-learn
          pip install clang==14.0
          pip install reportlab

      # --------------------------------
      # CREATE REQUIRED FOLDERS
      # --------------------------------
      - name: Create Required Folders
        run: |
          mkdir -p compiler-auto-vectorization-advisor/uploads

          mkdir -p compiler-auto-vectorization-advisor/static/reports

          mkdir -p compiler-auto-vectorization-advisor/static/graphs

      # --------------------------------
      # RUN AUTOMATION PIPELINE
      # --------------------------------
      - name: Run Automation Pipeline
        run: |
          cd compiler-auto-vectorization-advisor

          python automation_runner.py

      # --------------------------------
      # UPLOAD REPORTS + GRAPHS
      # --------------------------------
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4

        with:
          name: optimization-results

          path: |
            compiler-auto-vectorization-advisor/static/reports/
            compiler-auto-vectorization-advisor/static/graphs/
