name: Compiler Optimization Benchmark

on:
  push:
    branches:
      - main

jobs:

  benchmark:

    runs-on: ubuntu-latest

    steps:

      # --------------------------------
      # CHECKOUT REPOSITORY
      # --------------------------------
      - name: Checkout Repository
        uses: actions/checkout@v4

      # --------------------------------
      # SETUP PYTHON
      # --------------------------------
      - name: Setup Python
        uses: actions/setup-python@v5

        with:
          python-version: "3.11"

      # --------------------------------
      # INSTALL GCC + LLVM
      # --------------------------------
      - name: Install Compilers
        run: |
          sudo apt update
          sudo apt install -y clang gcc llvm

      # --------------------------------
      # INSTALL PYTHON PACKAGES
      # --------------------------------
      - name: Install Python Packages
        run: |
          pip install flask
          pip install pandas
          pip install matplotlib
          pip install scikit-learn

      # --------------------------------
      # CREATE REQUIRED FOLDERS
      # --------------------------------
      - name: Create Required Folders
        run: |
          mkdir -p uploads
          mkdir -p static/reports

      # --------------------------------
      # RUN PROJECT
      # --------------------------------
      - name: Run Project
        run: |
          cd compiler-auto-vectorization-advisor
          python main.py
